###find all songs
GET http://localhost:3000/songs

###find single song 

GET http://localhost:3000/songs/1

###create a new song

POST http://localhost:3000/songs
Content-Type: application/json

{
    "title":"Bhojhe na se Bojhe na",
    "artists":["arijit",
    "Shreya",
    "Jubin"
    ],
    "releasedDate":"2015-06-06",
    "duration":"05:34"

}

###update a single song

PUT http://localhost:3000/songs/1

###delete a single song

DELETE http://localhost:3000/songs/1